### ISSUE TITLE
submit to hackage?

### ISSUE THREAD

**Issue by shapr** [f-me/dmcc#3]
Hey, I could benefit from this package, any reason it's not on hackage?

**Comment by unclechu** [comment]
@dzhus It's your chance to become a star!

**Comment by unclechu** [comment]
@dzhus If you don't mind, and if you don't personally want to take care of it, I could do that.

**Comment by dzhus** [comment]
@shapr Hi, are you looking to use the Haskell library or the Websocket/JSON API server? API documentation for the websocket server is lacking now – I'll brush up the readme and push to Hackage.

**Comment by unclechu** [comment]
I think this [PR](https://github.com/f-me/dmcc/pull/4) must be finished first. I also realized it won't compile with current LTS (I guess it's that mess with revisions in old LTS versions when they're isn't fixated).

**Comment by unclechu** [comment]
I'm going to finish that PR in near few days.

**Comment by shapr** [comment]
Hi @dzhus I'm interested in using the Haskell library, I just want to talk to avaya over dmcc, thanks

**Comment by dzhus** [comment]
@shapr It's now on Hackage

**Comment by shapr** [comment]
many thanks!
