### ISSUE TITLE
README: Добавить список того, что либа может делать

### ISSUE THREAD

**Issue by unclechu** [f-me/dmcc#5]
Хорошо бы добавить маркированный список фичур данной либы, перечислить что она вообще может делать. Желательно перед релизом на hackage (см. f-me/dmcc#3).

**Comment by dzhus** [comment]
Не поверишь, как раз нашёл в запасниках (git stash) патчик, где начинал писать раздел features :)

**Comment by unclechu** [comment]
I'm closing this as solved.
