### ISSUE TITLE
Avaya dmcc with asp.net core 2.1

### ISSUE THREAD

**Issue by AhmadWaheedQadri** [f-me/dmcc#8]
This is not a bug report or any feature request.
My issue is that I have been asked to enable cti Intigration with avaya one x softphone. I have found an application (.net framework 2.0) that enables(provides) all the telephony features. But my concern is that, I have to communicate to the avaya one x using my web portal which is created using angular 5 and asp.net core2.1. So how should I go about this .. I have red about web sockets, WCF etc..
My situation is, I have a web deployed on a server. The dmcc application will be running on all client pc. And whenever a client opens the web app and login, he/she must be able to contrll the avaya softphone on that PC using that web portal.
Any help would be highly appreciated..I only need the structural view of this solution..

**Comment by dzhus** [comment]
@AhmadWaheedQadri

1) One-X softphone does have a REST API that you can talk to over HTTP. So the softphone runs a local HTTP server that you can in theory talk to right from your client code: <https://www.devconnectprogram.com/site/global/products_resources/avaya_one_x_agent/interfaces/one_x_agent_api/overview/index.gsp>. One issue we found with this API is that it doesn't support CORS headers and the browser may complain about security violation:
    ```
    XMLHttpRequest cannot load 
    http://localhost:60000/onexagent/api/registerclient?name=test. 
    'Access-Control-Allow-Origin' header is present on the requested 
    resource. 
    Origin http://192.168.10.15:8000 is therefore not allowed access. 
    ```
    This has nothing to do with DMCC API though.

2) Use DMCC API to integrate your .Net backend with AVAYA server and then provide endpoints in your backend to integrate your client code with. So your client code would talk to your backend, which would talk to AVAYA server via DMCC API, which would in turn drive softphones as expected. You can in theory try to run `dmcc-ws` from this repository and interact with this service instead.

What do you mean by "The dmcc application"?

**Comment by AhmadWaheedQadri** [comment]
Thank you so much for the response, I was beginning to loose hope.
a) By "The dmcc application" I mean the sample application provided by avaya (popup Applicaiton).
b) Should I not go for the javascript softphone client provided by avaya? which Im finding hard to understand.
c) "Use DMCC API to integrate your .Net backend with AVAYA server and then provide endpoints in your backend to integrate your client code with" by this do you mean the telephony logic will reside on the server (StartApplicationSession, getDeviceId and so on).
Ill now check the link..

**Comment by dzhus** [comment]
>  by this do you mean the telephony logic will reside on the server (StartApplicationSession, getDeviceId

Yes – DMCC API is intended to be used by server apps.
